name: Chrome VNC Docker container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t chrome-vnc .

      - name: Run Docker container
        run: |
          docker run --name vnc-container -p8080:80 -d chrome-vnc

      - name: Install LocalTunnel
        run: |
          sudo npm install -g localtunnel

      - name: Create LocalTunnel
        run: |
          lt --port 8080 --subdomain chrome.primordials
          

